version: "3"

services:
  db:
    build:
      context: ./db
    restart: always
    ports: 
      - "5433:5432"
    volumes:
      - ./db/init_db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"

volumes:
  db-store:
